config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|vi/ do
    root to: "static_pages#home"
    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    resources :users
    resources :products
    resources :account_activations, only: %i(edit)
    resources :password_resets, only: %i(new create edit update)
  end
end

app/views/layouts/_banner.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators">
			<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
			<li data-target="#myCarousel" data-slide-to="1" class=""></li>
			<li data-target="#myCarousel" data-slide-to="2" class=""></li>
			<li data-target="#myCarousel" data-slide-to="3" class=""></li>
			<li data-target="#myCarousel" data-slide-to="4" class=""></li> 
		</ol>
		<div class="carousel-inner" role="listbox">
			<div class="item active"> 
				<div class="container">
					<div class="carousel-caption">
						<h3>The Biggest <span>Sale</span></h3>
						<p>Special for today</p>
						<a class="hvr-outline-out button2" href="mens.html">Shop Now </a>
					</div>
				</div>
			</div>
			<div class="item item2"> 
				<div class="container">
					<div class="carousel-caption">
						<h3>Summer <span>Collection</span></h3>
						<p>New Arrivals On Sale</p>
						<a class="hvr-outline-out button2" href="mens.html">Shop Now </a>
					</div>
				</div>
			</div>
			<div class="item item3"> 
				<div class="container">
					<div class="carousel-caption">
						<h3>The Biggest <span>Sale</span></h3>
						<p>Special for today</p>
						<a class="hvr-outline-out button2" href="mens.html">Shop Now </a>
					</div>
				</div>
			</div>
			<div class="item item4"> 
				<div class="container">
					<div class="carousel-caption">
						<h3>Summer <span>Collection</span></h3>
						<p>New Arrivals On Sale</p>
						<a class="hvr-outline-out button2" href="mens.html">Shop Now </a>
					</div>
				</div>
			</div>
			<div class="item item5"> 
				<div class="container">
					<div class="carousel-caption">
						<h3>The Biggest <span>Sale</span></h3>
						<p>Special for today</p>
						<a class="hvr-outline-out button2" href="mens.html">Shop Now </a>
					</div>
				</div>
			</div> 
		</div>
		<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
			<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
		<!-- The Modal -->
    </div> 

app/views/layouts/_footer.html.erb
<footer>
<div class="footer">
  <div class="footer_agile_inner_info_w3l">
    <div class="col-md-3 footer-left">
      <h2><a href="index.html"><span>E</span>lite Shoppy </a></h2>
      <p>Lorem ipsum quia dolor
      sit amet, consectetur, adipisci velit, sed quia non 
      numquam eius modi tempora.</p>
      <ul class="social-nav model-3d-0 footer-social w3_agile_social two">
                              <li><a href="#" class="facebook">
                                  <div class="front"><i class="fa fa-facebook" aria-hidden="true"></i></div>
                                  <div class="back"><i class="fa fa-facebook" aria-hidden="true"></i></div></a></li>
                              <li><a href="#" class="twitter"> 
                                  <div class="front"><i class="fa fa-twitter" aria-hidden="true"></i></div>
                                  <div class="back"><i class="fa fa-twitter" aria-hidden="true"></i></div></a></li>
                              <li><a href="#" class="instagram">
                                  <div class="front"><i class="fa fa-instagram" aria-hidden="true"></i></div>
                                  <div class="back"><i class="fa fa-instagram" aria-hidden="true"></i></div></a></li>
                              <li><a href="#" class="pinterest">
                                  <div class="front"><i class="fa fa-linkedin" aria-hidden="true"></i></div>
                                  <div class="back"><i class="fa fa-linkedin" aria-hidden="true"></i></div></a></li>
                            </ul>
    </div>
    <div class="col-md-9 footer-right">
      <div class="sign-grds">
        <div class="col-md-4 sign-gd">
          <h4>Our <span>Information</span> </h4>
          <ul>
            <li><a href="index.html">Home</a></li>
            <li><a href="mens.html">Men's Wear</a></li>
            <li><a href="womens.html">Women's wear</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="typography.html">Short Codes</a></li>
            <li><a href="contact.html">Contact</a></li>
          </ul>
        </div>
        
        <div class="col-md-5 sign-gd-two">
          <h4>Store <span>Information</span></h4>
          <div class="w3-address">
            <div class="w3-address-grid">
              <div class="w3-address-left">
                <i class="fa fa-phone" aria-hidden="true"></i>
              </div>
              <div class="w3-address-right">
                <h6>Phone Number</h6>
                <p>+1 234 567 8901</p>
              </div>
              <div class="clearfix"> </div>
            </div>
            <div class="w3-address-grid">
              <div class="w3-address-left">
                <i class="fa fa-envelope" aria-hidden="true"></i>
              </div>
              <div class="w3-address-right">
                <h6>Email Address</h6>
                <p>Email :<a href="mailto:example@email.com"> mail@example.com</a></p>
              </div>
              <div class="clearfix"> </div>
            </div>
            <div class="w3-address-grid">
              <div class="w3-address-left">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
              </div>
              <div class="w3-address-right">
                <h6>Location</h6>
                <p>Broome St, NY 10002,California, USA. 
                
                </p>
              </div>
              <div class="clearfix"> </div>
            </div>
          </div>
        </div>
        <div class="col-md-3 sign-gd flickr-post">
          <h4>Flickr <span>Posts</span></h4>
          <ul>
            <li><a href="single.html"><img src="images/t1.jpg" alt=" " class="img-responsive" /></a></li>
            <li><a href="single.html"><img src="images/t2.jpg" alt=" " class="img-responsive" /></a></li>
            <li><a href="single.html"><img src="images/t3.jpg" alt=" " class="img-responsive" /></a></li>
            <li><a href="single.html"><img src="images/t4.jpg" alt=" " class="img-responsive" /></a></li>
            <li><a href="single.html"><img src="images/t1.jpg" alt=" " class="img-responsive" /></a></li>
            <li><a href="single.html"><img src="images/t2.jpg" alt=" " class="img-responsive" /></a></li>
            <li><a href="single.html"><img src="images/t3.jpg" alt=" " class="img-responsive" /></a></li>
            <li><a href="single.html"><img src="images/t2.jpg" alt=" " class="img-responsive" /></a></li>
            <li><a href="single.html"><img src="images/t4.jpg" alt=" " class="img-responsive" /></a></li>
          </ul>
        </div>
        <div class="clearfix"></div>
      </div>
    </div>
    <div class="clearfix"></div>
      <div class="agile_newsletter_footer">
          <div class="col-sm-6 newsleft">
        <h3>SIGN UP FOR NEWSLETTER !</h3>
      </div>
      <div class="col-sm-6 newsright">
        <form action="#" method="post">
          <input type="email" placeholder="Enter your email..." name="email" required="">
          <input type="submit" value="Submit">
        </form>
      </div>

    <div class="clearfix"></div>
  </div>
  </div>
</div>
</footer>

app/views/layouts/_header.html.erb
<!-- header -->
<div class="header" id="home">
  <div class="container">
    <ul>
      <li><i class="fa fa-phone" aria-hidden="true"></i>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <a href="upload.html">Kênh Nhà Thiết kế</a>
          <% else %> 
            <a href="upload.html">Chào <%= current_user.name %></a>
          <% end %>
        <% end %>
      </li>
      <li></li>
    </ul>
  </div>
</div>
<!-- //header -->
<!-- header-bot -->
<div class="header-bot">
  <div class="header-bot_inner_wthreeinfo_header_mid">
    <div class="col-md-4 header-middle">
      <form action="#" method="post">
        <input type="search" name="search" placeholder="Search here..." required="">
        <input type="submit" value=" ">
        <div class="clearfix"></div>
      </form>
    </div>
    <!-- header-bot -->
    <div class="col-md-4 logo_agile">
      <h1><a href="index.html"><span>3D</span>Shopping <i class="fa fa-shopping-bag top_logo_agile_bag" aria-hidden="true"></i></a></h1>
    </div>
    <!-- header-bot -->
    <!-- <div class="col-md-4 agileits-social top_content">
      <ul class="social-nav model-3d-0 footer-social w3_agile_social">
        <li class="share">Share On : </li>
        <li>
          <a href="#" class="facebook">
            <div class="front"><i class="fa fa-facebook" aria-hidden="true"></i></div>
            <div class="back"><i class="fa fa-facebook" aria-hidden="true"></i></div>
          </a>
        </li>
        <li>
          <a href="#" class="twitter">
            <div class="front"><i class="fa fa-twitter" aria-hidden="true"></i></div>
            <div class="back"><i class="fa fa-twitter" aria-hidden="true"></i></div>
          </a>
        </li>
        <li>
          <a href="#" class="instagram">
            <div class="front"><i class="fa fa-instagram" aria-hidden="true"></i></div>
            <div class="back"><i class="fa fa-instagram" aria-hidden="true"></i></div>
          </a>
        </li>
        <li>
          <a href="#" class="pinterest">
            <div class="front"><i class="fa fa-linkedin" aria-hidden="true"></i></div>
            <div class="back"><i class="fa fa-linkedin" aria-hidden="true"></i></div>
          </a>
        </li>
      </ul>
    </div> -->
    <div class="clearfix"></div>
  </div>
</div>
<!-- //header-bot -->
<div class="ban-top">
  <div class="container">
    <div class="top_nav_left">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse menu--shylock" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav menu__list">
          <li class="active menu__item menu__item--current">
            <%= link_to root_path, class: "menu__link" do %>
              <%= t(".home") %>
              <span class="sr-only">(current)</span>
            <% end %>
          </li>
          <li class=" menu__item">
            <%= link_to products_path, class: "menu__link" do %>
              <%= t("Clothe_models_3D") %>
            <% end %>
          </li>
          <li class="dropdown menu__item">
            <a href="#" class="dropdown-toggle menu__link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Men's wear <span class="caret"></span></a>
              <ul class="dropdown-menu multi-column columns-3">
                <div class="agile_inner_drop_nav_info">
                  <div class="col-sm-6 multi-gd-img1 multi-gd-text ">
                    <a href="mens.html"><img src="images/top2.jpg" alt=" "/></a>
                  </div>
                  <div class="col-sm-3 multi-gd-img">
                    <ul class="multi-column-dropdown">
                      <li><a href="mens.html">Clothing</a></li>
                      <li><a href="mens.html">Caps & Hats</a></li>
                    </ul>
                  </div>
                  <div class="col-sm-3 multi-gd-img">
                    <ul class="multi-column-dropdown">
                      <li><a href="mens.html">Jewellery</a></li>
                      <li><a href="mens.html">Swimwear</a></li>
                    </ul>
                  </div>
                  <div class="clearfix"></div>
                </div>
              </ul>
          </li>
          <% if logged_in? %>
            <% if current_user.admin? %>
              <li class="menu__item menu__item--current">
                <%= link_to "#", class: "menu__link" do %>
                  <%= t(".your_designs") %>
                  <span class="sr-only">(current)</span>
                <% end %>
              </li>
            <% end %>
          <% end %>
          <li class=" menu__item">
            <%= link_to help_path, class: "menu__link" do %>
              <%= t("Contact") %>
            <% end %>    
          </li>
          </ul>
        </div>
        </div>
      </nav>  
    </div>
    <div class="top_nav_right">
      <!-- <div class="wthreecartaits wthreecartaits2 cart cart box_1"> 
            <form action="#" method="post" class="last"> 
            <input type="hidden" name="cmd" value="_cart">
            <input type="hidden" name="display" value="1">
            <button class="w3view-cart" type="submit" name="submit" value=""><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></button>
          </form>  
  
            </div> -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
        <div class="collapse navbar-collapse menu--shylock" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav menu__list">
          <% if logged_in? %>
            <li class="menu__item dropdown">
              <%= link_to "#", class: "menu__link dropdown-toggle",
                data: {toggle: "dropdown"} do %>
                <%= t "accout.accout" %>
                <%= content_tag "b", "", class: "caret" %>
              <% end %>
              <ul class="dropdown-menu agile_short_dropdown">
                <li><%= link_to t("accout.profile"), current_user %></li>
                <li><%= link_to t("accout.setting"), edit_user_path(current_user) %></li>
                <% if current_user.admin? %>
                  <li>
                    <%= link_to t("your_designs"), edit_user_path(current_user) %>
                  </li>
                <% end %>
                <li class="divider"></li>
                <li>
                  <%= link_to t("accout.log_out"), logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li>
              <%= link_to login_path, class: "menu__link" do %>
              <%= t("accout.log_in") %>
            <% end %>
            </li>
          <% end %>
          </ul>
        </div>
        </div>
      </nav>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track":
      "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic' rel='stylesheet' type='text/css'>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>